export const detailsListMapping= {
    status:{
        assignRM:"AssigneeName",
        status:"Status",
        dueDate:"DueDate",
        expectDate:"ExpectedConversionDate",
        priority:"Priority",
        localComponentName:"InternalInformation.AnchorCompanyLocalName",
        englishComponentName:"InternalInformation.AnchorCompanyEnglishName",
        ID:"AssigneeID",
        Salesrevenue:"SalesRevenue",
        RegisteredCapital:"",
        Numberofemployees:"NumberOfEmployees",
        Industry:"Industry",
        Phone:"",
        Website:"Website"
    },
    contactInformation:{
        chineseName:"Local",
        englishName:"EnglishName",
        personalTitle:"Title",
        gender:"Gender",
        primaryNumber:"PrimaryPhone",
        secondNumber:"SecondaryPhone",
        primaryEmail:"PrimaryEmail",
        secondEmail:"SecondaryEmail",
        contactAddress:"",
        contactCountry:"",
        contactProvience:"Location",
        referralEvent:""
    },
    InternalInformation:{
        financingInfo:"InternalInformation.FinancingInformation",
        customInfo:"InternalInformation.CustomsInformation",
        registrationType:"InternalInformation.RegistrationType",
        isAMHcustomer:"InternalInformation.ExistingAMHCustomer",
        anchorRelationship:"InternalInformation.AnchorCompanyRelationship",
        anchorLocalName:"InternalInformation.AnchorCompanyLocalName",
        anchorEnglishName:"InternalInformation.AnchorCompanyEnglishName",
        anchorRM:"InternalInformation.AnchorRM",
        extCustomerSegment:"InternalInformation.ExistingCustomerSegment",
        overseasInverstmentEnterprises:"InternalInformation.OverseaInvestemtEnterprise",
        currentFinancingStage:"InternalInformation.CurrentFinancingStage",
        keyProduceName:"InternalInformation.KeyProductName",
        hubCode:"InternalInformation.HUBCustomerCode",
        dateFounded:"DateFounded"
    },
    keyPerson:{
        chineseName:"Local",
        englishName:"EnglishName",
        personalTitle:"Title",
        gender:"Gender",
        contactProvience:"Location"
    }
}