export const detailsListMapping= {
    status:{
        assignRM:"AssigneeName",
        status:"Status",
        dueDate:"DueDate",
        expectDate:"DateFounded",
        priority:"Priority",
        localComponentName:"InternalInformation.AnchorCompanyLocalName",
        englishComponentName:"InternalInformation.AnchorCompanyEnglishName",
        ID:"AssigneeID",
        Salesrevenue:"SalesRevenue",
        RegisteredCapital:"",
        Numberofemployees:"NumberOfEmployees",
        Industry:"Industry",
        Phone:"",
        Website:"Website"
    },
    contactInformation:{
        chineseName:"LocalName",
        englishName:"EnglishName",
        personalTitle:"",
        gender:"",
        primaryNumber:"",
        secondNumber:"",
        primaryEmail:"",
        secondEmail:"",
        contactAddress:"",
        contactCountry:"",
        contactProvience:"",
        referralEvent:""
    },
    InternalInformation:{
        financingInfo:"InternalInformation.FinancingInformation",
        customInfo:"InternalInformation.CustomsInformation",
        registrationType:"InternalInformation.RegistrationType",
        isAMHcustomer:"InternalInformation.ExistingAMHCustomer",
        anchorRelationship:"InternalInformation.AnchorCompanyRelationship",
        anchorLocalName:"InternalInformation.AnchorCompanyLocalName",
        anchorEnglishName:"InternalInformation.AnchorCompanyEnglishName",
        anchorRM:"InternalInformation.AnchorRM",
        extCustomerSegment:"InternalInformation.ExistingCustomerSegment",
        overseasInverstmentEnterprises:"InternalInformation.OverseaInvestemtEnterprise",
        currentFinancingStage:"InternalInformation.CurrentFinancingStage",
        keyProduceName:"InternalInformation.KeyProductName",
        hubCode:"InternalInformation.HUBCustomerCode",
        dateFounded:"DateFounded"
    },
    keyPerson:{
        localName:"",
        englishName:"",
        contactPersonalTitle:"",
        gender:"",
        city:""
    }
}